# Generated by Django 4.0 on 2023-06-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoaWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.CharField(blank=True, max_length=255)),
                ('payment_amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('outTradeNo', models.CharField(blank=True, max_length=255)),
                ('msisdn', models.CharField(blank=True, max_length=255)),
                ('tradeNo', models.CharField(blank=True, max_length=255)),
                ('transactionNo', models.CharField(blank=True, max_length=255)),
                ('payment_state', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed')], default='PENDING', max_length=9)),
                ('boa_webhook_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='telebirr.boawebhook')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrackRevenueRatePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purcahsed_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.CharField(max_length=255)),
                ('trackId', models.CharField(max_length=255)),
                ('isPurcahsed', models.BooleanField(default=False)),
                ('track_price_amount', models.IntegerField(default=0)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telebirr.payment_info')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purcahsed_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.CharField(max_length=255)),
                ('albumId', models.CharField(max_length=255)),
                ('isPurcahsed', models.BooleanField(default=False)),
                ('album_price_amount', models.IntegerField(default=0)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telebirr.payment_info')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
