# Generated by Django 4.0 on 2023-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telebirr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackRevenueRatePercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate", models.IntegerField(default=5)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
