# Generated by Django 4.0 on 2023-04-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("telebirr", "0002_payment_info_boa_webhook_id"),
        ("gift", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift_payment_info",
            name="boa_webhook_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="telebirr.boawebhook",
            ),
        ),
    ]
